-- ページ管理テーブルの作成
CREATE TABLE IF NOT EXISTS pages (
  id INT NOT NULL,
  path TEXT NOT NULL,
  title VARCHAR(255) NOT NULL UNIQUE,
  content TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- 採番テーブルの作成
CREATE TABLE IF NOT EXISTS sequence (
  id INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
);

-- ユーザー管理テーブルの作成
CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- 画像管理テーブルの作成
CREATE TABLE IF NOT EXISTS images (
  id INT NOT NULL AUTO_INCREMENT,
  page_id INT NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  path TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (page_id) REFERENCES pages(id)
);